import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yoshi Zen",
  description: "Generated by yoshi-zen",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          inter.className,
          "grid grid-rows-[50px_1fr_40px] h-[calc(100dvh)] w-screen"
        )}
      >
        <header className="bg-yellow-50">ヘッダーだよ</header>
        {children}
        <footer className="bg-green-100">フッターだよ</footer>
      </body>
    </html>
  );
}
