import './globals.css';
import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });
import { Oswald } from 'next/font/google';

const oswaldFont = Oswald({ weight: '500', subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Yoshi's Portfolio Page",
  description: 'Generated by yoshi-zen',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={oswaldFont.className}>{children}</body>
    </html>
  );
}
